### ISSUE TITLE
TypeError: Cannot destructure property 'proxy' of 'this' as it is undefined. 

### ISSUE THREAD

**Issue by AliAhmedNada** [oracle/nosql-node-sdk#19]
I am facing this error while initializing my APP 

version : 5.3.3

TypeError: Cannot destructure property 'proxy' of 'this' as it is undefined.
    at /root/Desktop/orchestrator-SIT/alinma-orchestrator-sprint6/node_modules/https-proxy-agent/dist/agent.js:86:21
    at Generator.next (<anonymous>)
    at /root/Desktop/orchestrator-SIT/alinma-orchestrator-sprint6/node_modules/https-proxy-agent/dist/agent.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/Desktop/orchestrator-SIT/alinma-orchestrator-sprint6/node_modules/https-proxy-agent/dist/agent.js:4:12)
    at callback (/root/Desktop/orchestrator-SIT/alinma-orchestrator-sprint6/node_modules/https-proxy-agent/dist/agent.js:85:16)
    at Function.writeFieldValue (/root/Desktop/orchestrator-SIT/alinma-orchestrator-sprint6/node_modules/oracle-nosqldb/lib/binary_protocol/protocol.js:165:19)
    at Function._writeMapEntries (/root/Desktop/orchestrator-SIT/alinma-orchestrator-sprint6/node_modules/oracle-nosqldb/lib/binary_protocol/protocol.js:100:18)
    at Function.writeObject (/root/Desktop/orchestrator-SIT/alinma-orchestrator-sprint6/node_modules/oracle-nosqldb/lib/binary_protocol/protocol.js:112:14)
    at Function.writeFieldValue (/root/Desktop/orchestrator-SIT/alinma-orchestrator-sprint6/node_modules/oracle-nosqldb/lib/binary_protocol/protocol.js:223:26)

**Comment by y-polonsk** [comment]
Hi,
Can you please provide more info about your app?  This error does not seem to be related to the SDK. In particular, what is https-proxy-agent module?
